site_name: DSM - Dubbo Service Mesh for Kubernetes
site_url: https://dubbo-kubernetes.github.io/dsm-docs/
use_directory_urls: true

repo_name: dubbo-kubernetes
repo_url: https://github.com/apache/dubbo-kubernetes

theme:
  name: material
  language: zh # 默认语言
  custom_dir: overrides
  favicon: assets/static/logo.png
  logo: assets/static/logo.png
  font: false
  palette:
    scheme: default
    primary: teal
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.instant

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

plugins:
  - i18n:
      default_language: zh
      languages:
        - locale: en
          name: English
          default: false
        - locale: zh
          name: 中文
          default: true
          fallback_to_default: true
      # 导航栏翻译依然保持这种字典格式
      nav_translations:
        zh:
          Overview: 概述
          Getting Started: 入门
          Installation: 安装指南
          User Guide: 用户指南
          Upgrade Guide: 升级指南
  - search:
      lang: [en, zh]

extra_css:
  - assets/custom.css

extra_javascript:
  - assets/custom.js

nav:
#  - Home: index.md
#  - Getting Started: getting-started.md
#  - User Guide:
#      - Overview: user-guide/index.md
#      - Installation: user-guide/installation.md
#      - Configuration: user-guide/configuration.md
  - 概述: overview/index.md
  - 概念: getting-started.md
  - 安装指南: installation.md
  - 任务: tasks.md
  - 运维: operation.md
  - 版本发布: release.md
  - 参考: reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/apache/dubbo-kubernetes

copyright: Copyright © 2026 The Dubbo Kubernetes Team.