site_name: DSM - Dubbo Service Mesh for Kubernetes
site_url: https://dubbo-kubernetes.github.io/dsm-docs/
use_directory_urls: true

repo_name: dubbo-kubernetes
repo_url: https://github.com/apache/dubbo-kubernetes

theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: assets/static/favicon.ico
  logo: assets/static/logo.png
  font: false
  palette:
    scheme: default
    primary: teal
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

plugins:
  - search:
      lang: [en, zh]

extra_css:
  - assets/custom.css

extra_javascript:
  - assets/custom.js

nav:
  - 概述:
    - overview/index.md
    - 入门: overview/getting_started.md
  - 概念（待补充）:
      - 流量管理: concepts/traffic-management.md
      - 安全: concepts/security.md
      - 可观测（开发中）: concepts/observability.md
  - 安装指南:
    - dubboctl: setup/install/dubboctl.md
    - helm: setup/install/helm.md
  - 任务:
      - 流量管理:
           - 路由规则:
               - 流量切分: tasks/traffic/canary/canary.md
           - Ingress:
               - Kubernetes Gateway API: tasks/traffic/ingress/gateway-api.md
      - 安全:
          - 双向 TLS: tasks/security/mtls.md
      - 可观测（开发中）: tasks/observability/_index.md
  - 运维（待补充）: operation.md
  - 版本发布（待补充）: release.md
  - 参考（待补充）: reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/apache/dubbo-kubernetes

copyright: Copyright © 2026 The Dubbo Kubernetes Team.